### PR TITLE
If PyQt5.Qt not working, use clipboard instead

### PR DESCRIPTION
**Pull request by zeze-zeze**
**Environment:**
Python 3.9
IdaPro 7.5

**Description:**
When the plugin loading, it gives the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'QApplication' from 'PyQt5.Qt'
```

Even I tried to use `from PyQt5.QtWidgets import QApplication`, but I got the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing sip: The specified module could not be found.
```

After some searching, I found the [issue](https://github.com/igogo-x86/HexRaysPyTools/issues/48), while the solution of the issue is not working on python3.9, either.

As a result, I use clipboard to copy and paste the name and address instead of QApplication, so it will import and use clipboard if  there is any error while using QApplication.

### CODE REVIEW

**Comment by zeze-zeze** [comment]
Oh, I finally found the answer.
There is a file called "sip.cp39-win_amd64.pyd" in python3.9 library, and replace sip.pyd in IDA7.5\python\3\PyQt5 with it.

I think the PR is no longer needed, so I close it.

**Comment by whokilleddb** [comment]
> Oh, I finally found the answer. There is a file called "sip.cp39-win_amd64.pyd" in python3.9 library, and replace sip.pyd in IDA7.5\python\3\PyQt5 with it.
> 
> I think the PR is no longer needed, so I close it.

You are a beautiful beautiful person @zeze-zeze :)

**Comment by 0xKira** [comment]
[Auto Reply]已收到您的邮件。——Kira

**Comment by ghost** [comment]
@zeze-zeze  you are gorgeous！thank you!
